apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: ecommerce
spec:
  encryptedData:
    password: AgAeK6H/rafepr8/K7dlUjbpD3jN4hWpw7+4hB7sjjRTX3pKAACE0gLcgUix2opIN4MACcxPPpJEc93Dr9bcrj7IDeqXAstB0gXU0wmxpt1wDzyUwy2eqIm2wa+4jiYhXP+G4OgnmB4qT0/pVdgk9hpR720hkV3yS6UB2jKVTgJ9sTydrGL9uzPI2olaSkBB4xo3xMSFlY+mYIqQ3NxfWzB50OAQpnsd3/5LVZg0WhUpD/7tAKQesjeZaSmGhZcqQBLt+BssQv7vejF/ZsDICpWE/cLxq5Fhb3fev0SNr00H2gv6PkcPqaCWbqt8sEhXXi9ekyR9gtG5uKYd7JVHYp1xgVGje1uh+6SBLugUFkbp2WPakFOyyVLQJCUQBwHnCsHuHrAI+inRu+BToOMk8tjbOroxC+uJkvRBZzf2IysOrpkMzdKfdfpApzZkEbS0zIVcG8IwlYhImIyaaBlBg28Mh5IjMuDhvxkhAzugks+uOYIU30FHmoEg+g0FQbHdArGLYEEDe/U8uYhHjSN1Oh3mJ4w6IAlBnpjiU4JF5tiQXH4/ua0AtR1QySYty1d0eTIVEASJA6jU9bUa+AhGfnH32FISX8bnXhv2vvxBApcuUb4f9KLT7PDJXjHCp0L4UZ2M0lNF7G2aNOnPogAF0LCKf2XrWwQK5yRN6O7N7Mvndnini1QzHf91AWEtg4T4X3YzdmgcqccQVsI=
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: ecommerce
---
